src/nmdb/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nmdb.pages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("nmdb.users.urls")),
    path("movies/", include("nmdb.movies.urls")),
    path("news/", include("nmdb.news.urls")),
    # path("shop/", include("nmdb.shop.urls")),
    path("api/v1/", include("nmdb.apiv1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

src/nmdb/movies/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.MovieListView.as_view(), name="movie-list"),
    path("add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("<slug>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("<slug>/edit/", views.MovieUpdateView.as_view(), name="movie-edit"),
    path("<slug>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),
    path("<int:pk>/review/", views.review_movie, name="movie-review"),
]

src/nmdb/movies/models.py
from __future__ import annotations

import secrets

from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.staticfiles.storage import staticfiles_storage
from django.db import models, transaction
from django.db.models import Q
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager

from nmdb.core.models import BaseModel
from nmdb.core.utils import markdown
from nmdb.photos.models import Photo

_poster_sizes = frozenset(
    [
        "xl",
        "lg",
        "md",
        "sm",
        "xs",
        "thumb",
    ]
)


def generate_slug(movie: Movie, new_slug: str | None = None) -> str:
    if new_slug is not None and new_slug.strip():
        slug = new_slug
    else:
        slug = slugify(movie.title)

    slug_exists = movie.__class__.objects.filter(slug=slug).exists()
    if slug_exists:
        rand = secrets.token_hex(2)
        new_slug = f"{slug}-{rand}"
        return generate_slug(movie, new_slug=new_slug)

    return slug


class Genre(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="children",
    )

    class MPTTMeta:
        order_insertion_by = ["name"]

    def __str__(self) -> str:
        return self.name


class Person(BaseModel):
    name = models.CharField(
        _("name"),
        max_length=255,
        help_text=_("Person's full name"),
    )
    birthdate = models.DateField(_("birthdate"), null=True, blank=True)
    bio = models.TextField(_("bio"), null=True, blank=True)
    photos = GenericRelation(Photo, related_query_name="person")

    class Meta:
        db_table = "people"
        verbose_name = _("person")
        verbose_name_plural = _("people")

    def __str__(self) -> str:
        return f"{self.name}"

    @cached_property
    def bio_html(self) -> str:
        if self.bio is None:
            return "N/A"
        return markdown.parse(self.bio)

    @cached_property
    def mug(self) -> Photo | None:
        return self.photos.filter(is_primary=True).first()

    def _get_default_pic_url(self, size=None) -> str:
        name = "mug"
        if size in _poster_sizes:
            name = f"{name}_{size}"
        path = f"images/people/{name}.png"
        return staticfiles_storage.url(path)

    def get_pic_url(self, size=None):
        if self.mug is None:
            return self._get_default_pic_url(size=size)

        if size is None or size not in _poster_sizes:
            size = "photo"

        photo = getattr(self.mug, size, self.mug.photo)

        return photo.url


class Movie(BaseModel):
    class Ratings(models.TextChoices):
        G = "G", _("G: General Audiences")
        PG = "PG", _("PG: Parental Guidance Suggesteds")
        PG13 = "PG-13", _("PG-13: Parents Strongly Cautioned")
        R = "R", _("R - Restricted")
        NC17 = "NC-17", _("NC-17: Adults Only")

    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"), max_length=255, unique=True)
    year = models.IntegerField(_("year"), help_text=_("Movie's release year"))
    plot = models.TextField(_("plot"), null=True, blank=True)
    runtime = models.IntegerField(
        _("runtime"),
        null=True,
        blank=True,
        help_text=_("Movie runtime in minutes"),
    )
    mpaa_rating = models.CharField(
        max_length=5,
        null=True,
        blank=True,
        choices=Ratings.choices,
    )
    genre = models.ForeignKey(
        Genre,
        verbose_name=_("genre"),
        null=True,
        blank=True,
        related_name="movies",
        on_delete=models.SET_NULL,
    )
    director = models.ForeignKey(
        Person,
        verbose_name=_("director"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="movies_directed",
    )
    actors = models.ManyToManyField(Person, through="Role", related_name="movies")
    photos = GenericRelation(Photo, related_query_name="movie")
    tags = TaggableManager()

    class Meta:
        db_table = "movies"
        verbose_name = _("movie")
        verbose_name_plural = _("movies")
        constraints = [
            models.CheckConstraint(check=Q(year__gte=1900), name="chk_movies_year"),
            models.CheckConstraint(
                check=Q(runtime__gte=20) & Q(runtime__lte=480),
                name="chk_movies_runtime",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.title} ({self.year})"

    def get_absolute_url(self) -> str:
        return reverse("movies:movie-detail", kwargs={"pk": self.pk})

    @transaction.atomic
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_slug(self)
        return super().save(*args, **kwargs)

    @cached_property
    def poster(self) -> Photo | None:
        return self.photos.filter(is_primary=True).first()

    def _get_default_pic_url(self, size=None) -> str:
        name = "poster"
        if size in _poster_sizes:
            name = f"{name}_{size}"
        path = f"images/movies/{name}.png"
        return staticfiles_storage.url(path)

    def get_pic_url(self, size=None):
        if self.poster is None:
            return self._get_default_pic_url(size=size)

        if size is None or size not in _poster_sizes:
            size = "photo"

        photo = getattr(self.poster, size, self.poster.photo)

        return photo.url

    @cached_property
    def plot_html(self) -> str:
        if self.plot is None:
            return "N/A"
        return markdown.parse(self.plot)


class Role(models.Model):
    movie = models.ForeignKey(
        Movie,
        verbose_name=_("movie"),
        related_name="roles",
        on_delete=models.CASCADE,
    )
    actor = models.ForeignKey(
        Person,
        verbose_name=_("actor"),
        related_name="roles",
        on_delete=models.CASCADE,
    )
    role = models.CharField(_("role"), max_length=255)

    class Meta:
        db_table = "roles"
        verbose_name = _("role")
        verbose_name_plural = _("roles")

    def __str__(self) -> str:
        return self.role


class Review(BaseModel):
    movie = models.ForeignKey(
        Movie,
        verbose_name=_("movie"),
        related_name="reviews",
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("user"),
        related_name="reviews",
        on_delete=models.CASCADE,
    )
    rating = models.IntegerField(_("rating"))
    content = models.TextField(_("content"), null=True, blank=True)
    is_approved = models.BooleanField(_("is approved"), default=False)

    class Meta:
        db_table = "reviews"
        verbose_name = _("review")
        verbose_name_plural = _("reviews")
        permissions = [
            ("approve_review", "Can approve review"),
        ]
        constraints = [
            models.CheckConstraint(
                check=Q(rating__gte=1) & Q(rating__lte=5), name="chk_reviews_rating"
            ),
            models.UniqueConstraint(
                fields=["user", "movie"], name="uq_reviews_user_movie"
            ),
        ]

    def __str__(self) -> str:
        return f"{self.user!r} reviewd {self.movie!r} {self.rating} stars"

src/nmdb/movies/forms.py
import datetime as dt

from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            "title",
            "year",
            "runtime",
            "plot",
            "mpaa_rating",
            "director",
        ]

    def clean_year(self):
        today = dt.date.today()
        year = self.cleaned_data["year"]
        if year < 1900 or year > today.year + 1:
            raise forms.ValidationError("Invalid movie release year")
        return year

    def clean_runtime(self):
        runtime = self.cleaned_data["runtime"]
        if 20 <= runtime <= 600:
            return runtime
        raise forms.ValidationError("Movies last between 20 and 600 minutes only")


class ReviewForm(forms.Form):
    rating = forms.IntegerField(min_value=1, max_value=5, required=True)
    content = forms.CharField(required=False, widget=forms.Textarea)

src/nmdb/movies/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import (
    SearchHeadline,
    SearchQuery,
    SearchRank,
    SearchVector,
)
from django.db.models import Avg, F, Prefetch
from django.db.models.functions import Round
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views import generic
from django.views.decorators.http import require_POST

from nmdb.photos.models import Photo

from .forms import MovieForm, ReviewForm
from .models import Movie, Review, Role


class MovieListView(generic.ListView):
    context_object_name = "movies"
    paginate_by = 6

    def get_queryset(self):
        qs = (
            Movie.objects.prefetch_related(
                Prefetch("photos", Photo.objects.filter(is_primary=True).all())
            )
            .filter(photos__is_primary=True)
            .annotate(caption=F("photos__caption"))
            .annotate(avgrate=Round(Avg("reviews__rating"), precision=1))
        )

        search_query = self.request.GET.get("q", "").strip()
        if search_query:
            vector = SearchVector("title") + SearchVector("plot")
            query = SearchQuery(search_query)
            headline = SearchHeadline(
                "plot",
                query,
                start_sel="<mark>",
                stop_sel="</mark>",
            )

            qs = (
                qs.annotate(search=vector, rank=SearchRank(vector, query))
                .annotate(headline=headline)
                .filter(search=query)
                .order_by("-rank")
                .all()
            )
        else:
            qs = qs.order_by("-created_at").all()

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)

        page_number = int(self.request.GET.get(self.page_kwarg, "1"))
        paginator = context_data["paginator"]
        pages = paginator.get_elided_page_range(
            number=page_number,
            on_each_side=2,
        )

        search_query = self.request.GET.get("q", "").strip()

        context_data.update({"pages": pages, "search_query": search_query})
        return context_data


class MovieDetailView(generic.DetailView):
    context_object_name = "movie"

    def get_queryset(self):
        return Movie.objects.select_related("director").prefetch_related("photos").all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        movie = context_data[self.context_object_name]

        avg_rating = Review.objects.filter(movie=movie).aggregate(
            avgrating=Round(Avg("rating"), precision=1)
        )

        cast = (
            Role.objects.select_related("actor")
            .prefetch_related(
                Prefetch("actor__photos", Photo.objects.filter(is_primary=True).all())
            )
            .filter(movie=movie)
            .all()
        )

        user_rating = {"rating": None}
        if self.request.user.is_authenticated:
            user_rating["rating"] = (
                Review.objects.filter(movie=movie, user=self.request.user)
                .values_list("rating", flat=True)
                .first()
            )

        context_data.update({"cast": cast, **avg_rating, **user_rating})
        return context_data


class MovieCreateView(generic.CreateView):
    model = Movie
    form_class = MovieForm


class MovieUpdateView(generic.UpdateView):
    model = Movie
    form_class = MovieForm


class MovieDeleteView(generic.DeleteView):
    model = Movie
    success_url = reverse_lazy("movies:movie-list")


@login_required
@require_POST
def review_movie(request: HttpRequest, pk: int) -> HttpResponse:
    movie = get_object_or_404(Movie, pk=pk)
    form = ReviewForm(request.POST)
    if form.is_valid():
        review, created = Review.objects.update_or_create(
            user=request.user,
            movie=movie,
            defaults={"rating": form.cleaned_data["rating"]},
        )
        message = _("Thank you for updating your review.")
        if created:
            message = _("Thank you for your review.")
        current_rating = Review.objects.filter(movie=movie).aggregate(
            rating=Round(Avg("rating"), precision=1)
        )
        return JsonResponse({"detail": message, **current_rating})

    return JsonResponse(
        {
            "detail": _("Could not rate this movie"),
            "errors": form.errors,
        },
        status=400,
    )

src/nmdb/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load static i18n movietags %}

{% block title %}{{ movie.title }} · {{ block.super }}{% endblock title %}

{% block extrastyles %}
<link rel="stylesheet" href="{% static 'movies/styles/rate.css' %}">
{% endblock extrastyles %}

{% block content %}
  <div class="d-flex justify-content-between align-items-end my-2">
    <div>
      <h1 class="fs-3 m-0">{{ movie.title }}</h1>
      <h2 class="fs-6 fw-light text-muted">{{ movie.year }} · {{ movie.mpaa_rating }} · {{ movie.runtime|runtime }}</h2>
    </div>
    <div class="d-flex gap-5 justify-content-end">
      <div class="d-flex flex-column">
        <div class="text-center fs-5">{% translate "Rating" %}</div>
        <div class="d-flex gap-2">
          <i class="bi-star-fill fs-4 text-warning"></i>
          <div class="fs-4">
            <strong
              id="current-movie-rating"
              class="fw-semibold">
              {{ avgrating|floatformat:1|default:"-" }}
            </strong>
            <span class="text-muted fw-light">/</span>
            <em class="fw-light">5</em>
          </div>
        </div>
      </div>
      <div class="d-flex flex-column">
        <div class="text-center fs-5">{% translate "Your Rating" %}</div>
        {% if user.is_authenticated %}
        <div
            class="d-flex star-rate"
            data-rateurl="{% url 'movies:movie-review' pk=movie.pk %}"
            data-user-rating="{{ rating|default_if_none:0 }}">
          <i class="star-rate-star bi bi-star fs-4 text-warning px-1" data-rating="1"></i>
          <i class="star-rate-star bi bi-star fs-4 text-warning px-1" data-rating="2"></i>
          <i class="star-rate-star bi bi-star fs-4 text-warning px-1" data-rating="3"></i>
          <i class="star-rate-star bi bi-star fs-4 text-warning px-1" data-rating="4"></i>
          <i class="star-rate-star bi bi-star fs-4 text-warning px-1" data-rating="5"></i>
          {% csrf_token %}
        </div>
        {% else %}
        <div class="star-rate star-rate-disabled text-center">
          <i class="bi bi-slash-circle text-muted fs-4"
            data-bs-toggle="tooltip"
            data-bs-custom-class="danger-tooltip"
            data-bs-title="{% translate 'Only logged in users can vote!' %}"></i>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-6">
      <div id="carousel-movie-posters" class="carousel slide" data-bs-ride="true">
        <div class="carousel-indicators">
          {% for photo in movie.photos.all %}
          <button type="button" data-bs-target="#carousel-movie-posters" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="{{ photo }}"></button>
          {% endfor %}
        </div>
        <div class="carousel-inner">
          {% for photo in movie.photos.all %}
          <div class="carousel-item{% if forloop.first %} active{% endif %}">
            <img src="{{ photo.photo.url }}" class="d-block w-100" alt="{{ photo }}">
            <div class="carousel-caption d-none d-md-block">
              <h5>{{ photo.caption }}</h5>
              <p>{{ photo.description }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel-movie-posters" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">{% translate "Previous" %}</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel-movie-posters" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">{% translate "Next" %}</span>
        </button>
      </div>
    </div>
    <div class="col-6">
      <h1>{{ movie.title }}</h1>
      <section class="fs-4 fw-light mb-4">{{ movie.year }} · {{ movie.mpaa_rating }} · {{ movie.runtime|runtime }}</section>
      <section class="mb-4">{% translate "Director" %}: <strong>{{ movie.director }}</strong></section>
      <section class="mb-4">
        {% for tag in movie.tags.all %}
        <span class="badge text-bg-primary">{{ tag }}</span>
        {% endfor %}
      </section>
      <section>
        {{ movie.plot_html|safe }}
      </section>
      <h2 class="border-bottom">{% translate "Cast" %}</h2>
      <div class="d-flex flex-wrap">
        {% for member in cast %}
        <div class="d-flex gap-4 w-50 mb-2">
          {% for photo in member.actor.photos.all %}
          <img src="{{ photo.thumb.url }}"
               width="96" height="96"
               class="shadow-sm img-thumbnail rounded-circle"
               alt="{{ member.actor.name }}" />
          {% endfor %}
          <div class="d-flex flex-column flex-grow-1">
            <strong>{{ member.actor.name }}</strong>
            <span>as <em>{{ member.role }}</em></span>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="ratingToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="toast-icon bi bi-info-circle-fill me-2 text-primary"></i>
        <strong class="me-auto">{% translate 'Notification' %}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="{% translate 'Close' %}"></button>
      </div>
      <div class="toast-body"></div>
    </div>
  </div>
{% endblock %}

{% block extrascripts %}
<script>

</script>
<script src="{% static 'movies/scripts/rate.js' %}"></script>
{% endblock extrascripts %}

src/nmdb/movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% load i18n static imagekit movietags %}

{% block content %}
  <h1 class="border-bottom">{% translate "Movies" %}</h1>
  {% include "_pagination.html" with page_obj=page_obj pages=pages only %}
  <div class="row">
    {% for movie in movies %}
      <div class="col-6">
        <div class="card mb-4">
          <div class="row g-0">
            <div class="col-4">
              {% for photo in movie.photos.all %}
              <img src="{{ photo.lg.url }}" class="img-fluid rounded-start" alt="{{ movie.caption|default:movie.title }}">
              {% endfor %}
            </div>
            <div class="col-8">
              <div class="card-body position-relative">
                <a class="d-block card-title fs-4 text-decoration-none text-truncate"
                   href="{% url 'movies:movie-detail' slug=movie.slug %}"
                   data-bs-toggle="tooltip"
                   data-bs-title="{{ movie.title }}">
                  {{ movie.title }}
                </a>
                <div class="card-text">{{ movie.headline|default:movie.plot_html|truncatechars_html:"140"|safe }}</div>
                <div class="card-text">
                  <h2 class="fs-6 fw-light text-muted">{{ movie.year }} · {{ movie.mpaa_rating }} · {{ movie.runtime|runtime }}</h2>
                </div>
                <span class="badge bg-warning position-absolute top-0 start-100 p-2 translate-middle rounded-pill">
                  {{ movie.avgrate|default:"-.-" }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      {% if search_query %}
      <div class="alert alert-info" role="alert">
      {% blocktranslate %}
      We could not find any results for your search <strong>{{ search_query }}</strong>
      {% endblocktranslate %}
      </div>
      {% else %}
      <div class="alert alert-warning" role="alert">{% translate 'No movies have been added yet!' %}</div>
      {% endif %}
    {% endfor %}
</div>
{% endblock content %}