src/nmdb/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nmdb.pages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("nmdb.users.urls")),
    path("movies/", include("nmdb.movies.urls")),
    path("news/", include("nmdb.news.urls")),
    # path("shop/", include("nmdb.shop.urls")),
    path("api/v1/", include("nmdb.apiv1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

src/nmdb/movies/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.MovieListView.as_view(), name="movie-list"),
    path("add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("<slug>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("<slug>/edit/", views.MovieUpdateView.as_view(), name="movie-edit"),
    path("<slug>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),
    path("<int:pk>/review/", views.review_movie, name="movie-review"),
]

src/nmdb/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("<slug>/", views.PostDetailView.as_view(), name="post-detail"),
    path("add/", views.PostCreateView.as_view(), name="post-add"),
    path("<slug>/edit/", views.PostUpdateView.as_view(), name="post-edit"),
    path("<slug>/delete/", views.PostDeleteView.as_view(), name="post-delete"),
]

src/nmdb/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("about-us/", views.about_us, name="about-us"),
    path("contact-us/", views.contact_us, name="contact-us"),
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
]

src/nmdb/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
]

src/nmdb/templates/_pagination.html
<nav aria-label="Pagination" class="mb-4">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
        <i class="bi bi-chevron-double-left"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">
        <i class="bi bi-chevron-double-left"></i>
      </span>
    </li>
    {% endif %}
    {% for page in pages %}
    <li class="page-item{% if page == paginator.ELLIPSIS %} disabled{% endif %}">
      {% if page == paginator.ELLIPSIS %}
      <span class="page-link">{{ page }}</span>
      {% else %}
      <a class="page-link{% if page == page_obj.number %} active{% endif %}" href="?page={{ page }}{% if queryparams %}&{{ queryparams }}{% endif %}">{{ page }}</a>
      {% endif %}
    </li>
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a href="?page={{ page_obj.next_page_number }}" class="page-link">
        <i class="bi bi-chevron-double-right"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">
        <i class="bi bi-chevron-double-right"></i>
      </span>
    </li>
    {% endif %}
  </ul>
</nav>

src/nmdb/templates/base.html
<!doctype html>{% load static i18n %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% translate 'National movie database' %}">
    <meta name="author" content="Gledi">
    {% block meta %}{% endblock meta %}
    <title>{% block title %}National Movie Database · Python · Tirana · Albania · SDA{% endblock title %}</title>
    {% block styles %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Concert+One&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand page-title" href="{% url 'pages:home' %}">NMDb</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">{% translate 'Home' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'movies:movie-list' %}">{% translate 'Movies' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news:post-list' %}">{% translate 'News' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:contact-us' %}">{% translate 'Contact Us' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:about-us' %}">{% translate 'About Us' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:privacy-policy' %}">{% translate 'Privacy Policy' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="">{% translate 'Shop' %}</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="bi bi-cart4"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}">{% translate 'Logout' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' %}">{% translate 'Profile' %}</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">{% translate 'Login' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">{% translate 'Register' %}</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <form class="d-flex" role="search" method="get" action="{% url 'movies:movie-list' %}">
                  <input class="form-control me-2" type="search" placeholder="{% translate 'Search' %}" aria-label="{% translate 'Search' %}" name="q" {% if search_query %} value={{ search_query }}{% endif %}>
                  <button class="btn btn-outline-success" type="submit">{% translate 'Search' %}</button>
                </form>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="flex-shrink-0">
      <div class="container">
        {% if messages %}
        <section class="flash-messages">
          {% for message in messages %}
          <div role="alert" class="alert alert-{{ message.level_tag }}">
            {{ message }}
          </div>
          {% endfor %}
        </section>
        {% endif %}
        {% block content %}{% endblock content %}
      </div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <p class="text-center m-0 p-0 text-muted fw-semibold">Copyright &copy; 2022 · Python · Tirana · Albania · SDA</p>
      </div>
    </footer>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="{% static 'scripts/main.js' %}"></script>
    {% endblock scripts %}
    {% block extrascripts %}{% endblock extrascripts %}
  </body>
</html>